### ISSUE TITLE
NeetoUI Table checkbox issue

### ISSUE THREAD

**Issue by sayoojtmc** [sayoojtmc/neeto-ui-challenge-by-sayooj-surendran#16]
I was following neetoui docs for implementing checkbox feature in table.
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/32578593/203897275-4d4dd668-1a89-4a63-8f4e-b2d30c3520a4.png">

When I used the onRowSelect and log out selectedRowKeys ,
<img width="405" alt="image" src="https://user-images.githubusercontent.com/32578593/203897569-6fd083c1-de00-4428-a024-008b765d63a3.png">
I am getting undefined
<img width="608" alt="image" src="https://user-images.githubusercontent.com/32578593/203897613-0ae78ad3-a070-46f6-b532-6dc51e9f079e.png">

Please help solving this issue @yedhink

**Comment by sayoojtmc** [comment]
Fixed , apparently rowdata expects an id attribute which is taken by selectedRowKeys
<img width="366" alt="image" src="https://user-images.githubusercontent.com/32578593/203917381-5adc2f3d-d7d1-41b5-8861-9cd6af4932e8.png">

**Comment by yedhink** [comment]
@sayoojtmc Please put up a video in CH2022 Slack channel pointing out the following:
- What you were trying to implement?
- The issue that you faced
- How you tried to debug it
- What the solution was
